# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "vvvv"
    ansible.sudo = true
    ansible.playbook = "playbook.yml"
  end
end
